---
- name: Check PowerShell version
  hosts: vaultsyn
  tasks:
    - name: Retrieve PowerShell version
      win_shell: $PSVersionTable.PSVersion
      register: ps_version

    - name: Display PowerShell version
      debug:
        msg: "PowerShell version is {{ ps_version.stdout }}"
