---
- name: Deploy_Leader_Cluster_Conjur_Appliances
  hosts: leader, standbys

  tasks:
    - name: Checkout the code repository
      git:
        repo: 'https://github.com/GCLIM/conjur-appliance.git'
        dest: ~/conjur-appliance
        version: master
        update: yes

    - name: Install dependencies from requirements.txt
      pip:
        requirements: requirements.txt
      args:
        chdir: ~/conjur-appliance

    - name: Deploy Conjur appliances
      shell: |
        python3 conjur_appliance.py -m deploy -t {{ type }} -n {{ name }} -reg {{ registry }}
      args:
        chdir: ~/conjur-appliance
      register: result

    - name: Display results
      debug:
        var: result

