---
- name: Retire_Followers
  hosts: followers

  tasks:
    - name: Checkout the code repository
      git:
        repo: 'https://github.com/GCLIM/conjur-appliance.git'
        dest: ~/conjur-appliance
        version: master
        update: yes

    - name: Install dependencies from requirements.txt
      pip:
        requirements: requirements.txt
      args:
        chdir: ~/conjur-appliance

    - name: Retire Conjur appliances
      shell: |
        python3 conjur_appliance.py -m retire
      args:
        chdir: ~/conjur-appliance
      register: result

    - name: Display results
      debug:
        var: result

