leader:
  hosts:
    conjur01.gcloud101.com:
      ansible_host: 192.168.11.61
      name: leadernode
      type: leader
  vars:
    ansible_user: gclim
    registry: dockerhub.gcloud101.com/conjur-appliance:13.3.0.1
    load_balancer_dns: myconjur.gcloud101.com
    account_name: conjur_account

standbys: 
  hosts:
    conjur02.gcloud101.com:
      ansible_host: 192.168.11.62
      name: standbynode01
      type: standby
    conjur03.gcloud101.com:
      ansible_host: 192.168.11.63
      name: standbynode02
      type: standby
  vars:
    ansible_user: gclim
    registry: dockerhub.gcloud101.com/conjur-appliance:13.3.0.1

followers:
  hosts:
    conjur01.gcloud101.com:
      ansible_host: 192.168.11.61
      name: follower01
      type: follower
   conjur02.gcloud101.com:
      ansible_host: 192.168.11.62
      name: follower02
      type: follower
   conjur03.gcloud101.com:
      ansible_host: 192.168.11.63
      name: follower03
      type: follower