leader:
  hosts:
    conjur01.gcloud101.com:
      ansible_host: 192.168.11.61
      name: leadernode
      type: leader
  vars:
    ansible_user: gclim
    registry: dockerhub.gcloud101.com/conjur-appliance:13.3.0.1
    load_balancer_dns: conjur-dev-leader.gcloud101.com
    account_name: conjur_account
    ca_chain: /home/gclim/certificates/conjur-dev-leader-ca-chain.pem
    master_key: /home/gclim/certificates/conjur-dev-leader-master-key.pem
    master_cert: /home/gclim/certificates/conjur-dev-leader-master-cert.pem

standbys: 
  hosts:
    conjur02.gcloud101.com:
      ansible_host: 192.168.11.62
      name: standbynode01
      type: standby
    conjur03.gcloud101.com:
      ansible_host: 192.168.11.63
      name: standbynode02
      type: standby
  vars:
    ansible_user: gclim
    registry: dockerhub.gcloud101.com/conjur-appliance:13.3.0.1

followers:
  hosts:
    conjur01.gcloud101.com:
      ansible_host: 192.168.11.61
      name: follower01
      type: follower
    conjur02.gcloud101.com:
      ansible_host: 192.168.11.62
      name: follower02
      type: follower
    conjur03.gcloud101.com:
      ansible_host: 192.168.11.63
      name: follower03
      type: follower
  vars:
    ansible_user: gclim
    registry: dockerhub.gcloud101.com/conjur-appliance:13.3.0.1
    load_balancer_dns: conjur-dev.gcloud101.com
    follower_key: /home/gclim/cyberark/dap/certificates/conjur-dev-follower-key.pem
    follower_cert: /home/gclim/cyberark/dap/certificates/conjur-dev-follower-cert.pem

vaultsyn:
    hosts:
        vaultsyn.gcloud101.com:
            ansible_host: 192.168.1.100
            ansible_user: Administrator
            ansible_password: YourPassword
            ansible_connection: winrm
            ansible_winrm_server_cert_validation: ignore

#windows_host ansible_host=192.168.1.100 ansible_user=Administrator ansible_password=YourPassword ansible_connection=winrm ansible_winrm_server_cert_validation=ignore
