conjur_cluster:
  hosts:
    conjur01.gcloud101.com:
      ansible_host: 192.168.11.61
    conjur02.gcloud101.com:
      ansible_host: 192.168.11.62
    conjur03.gcloud101.com:
      ansible_host: 192.168.11.63
  vars:
    ansible_user: gclim