name: Conjur Retire All Appliances

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
    deploy:
        runs-on: conjur03
        environment: ${{ github.event.inputs.environment }}
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy Leader Cluster Node 1
              uses: appleboy/ssh-action@master
              with:
                    host: ${{ vars.TARGET_HOST_1 }}
                    username: ${{ vars.USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        cd conjur-appliance
                        python3 conjur_appliance.py -m retire

            - name: Deploy Leader Cluster Node 2
              uses: appleboy/ssh-action@master
              with:
                    host: ${{ vars.TARGET_HOST_2 }}
                    username: ${{ vars.USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        cd conjur-appliance
                        python3 conjur_appliance.py -m retire
