name: Conjur Leader Cluster Deployment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
    deploy:
        runs-on: conjur03
        environment: ${{ github.event.inputs.environment }}
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy code
              uses: appleboy/ssh-action@master
              with:
                    host: ${{ vars.TARGET_HOST_1 }}
                    username: ${{ vars.USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        if [ -d conjur ]; then
                          echo Conjur directory existed
                          echo clean up for redeployment
                          rm -Rf conjur
                        fi
                        git clone https://github.com/GCLIM/conjur-appliance.git conjur
                        cd conjur
                        git checkout master
                        python3 conjur_orchestrator.py -d leader -f env/dev/leader_cluster.yml