name: Conjur Leader Cluster Deployment (all)

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


before_script:
    - yum -y update
    - yum -y install gcc openssl-devel bzip2-devel libffi-devel
    - cd /usr/src
    - wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz
    - tar xzf Python-3.6.8.tgz
    - cd Python-3.6.8
    - ./configure --enable-optimizations
    - make altinstall
    - ln -s /usr/local/bin/python3.6 /usr/bin/python3.6
script:
    - python3.6 --version
    - python3.6 -m ensurepip
    - python3.6 -m pip install --upgrade pip
    - python3.6 -m pip install -r requirements.txt
    - python3.6 your_script.py

jobs:

    Pre-Checks:
        runs-on: conjur03
        environment: ${{ github.event.inputs.environment }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.6.8'  # Specify the Python version

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run script
              run: python3 conjur_orchestrator.py -g leader -f env/dev/leader_cluster.yml


