name: Deploy Leader Cluster

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
    Deploy_Leader_Cluster:
        runs-on: ansible
        environment: ${{ github.event.inputs.environment }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11.7 # Specify the Python version

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run script
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                SSH_USERNAME: ${{ vars.USER }}
                ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
              run: python3 conjur_orchestrator.py -d leader -i inventories/dev.yml


